name: CI Pipeline

on:
  push:
    branches: [master] # 触发条件：推送代码到 master 分支

jobs:
  build:
    runs-on: ubuntu-latest # 使用的运行器类型
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4 # 拉取代码

      - name: 安装NODEJS
        uses: actions/setup-node@v4
        with:
          node-version: "20" # 设置 Node.js 版本

      - name: 安装依赖
        run: npm install # 安装依赖

      - name: 打包项目
        run: npm run build # 打包项目

      - name: 下载构建产物
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts # 构建产物的名称
          path: ./dist # 打包文件所在的目录，根据项目实际情况修改
